### ISSUE TITLE
S’ is not a member of ‘sf::Text’   m_text.setStyle(sf::Text::S)

### ISSUE THREAD

**Issue by AssociationSirius** [namelessvoid/qrwar#105]
I sorry to say you that i can't compile qrwar on linux 18.04 with g++ 7.3

```
/opt/code/qrwar-master/src/foundation/textcomponent.cpp: In constructor ‘qrw::TextComponent::TextComponent(qrw::Layer)’:
/opt/code/qrwar-master/src/foundation/textcomponent.cpp:11:28: error: ‘S’ is not a member of ‘sf::Text’
  m_text.setStyle(sf::Text::S)
```

**Comment by namelessvoid** [comment]
Should be good now! I never expected anybody to actually compile this so I've been a bit messy with my check-ins lately, sorry!

**Comment by AssociationSirius** [comment]
Hi, can you commit the modification ? :)

**Comment by namelessvoid** [comment]
Hi, the fix (https://github.com/namelessvoid/qrwar/commit/4458b91bb11424d9415bacf5aa96800291c8e924#diff-91542e13cfcc92e44a1f4a9bf0c6fe36L11) is now pushed to the `master` branch.

Please let me know if you have any further issues. Since I'm building this project on my Arch Linux, there could be more hurdles on Ubuntu based systems, e.g. different versions of third-party libraries provided by the distro's repositories. However I'd be glad to provide fixes for you!
